#!/usr/bin/env sh

if [[ $1 == '-i' ]]; then
  c() {
    rm -f tmp.txt
  }
  trap c EXIT
  nvim --clean \
    -c "lua package.path = package.path .. ';./?.lua;../?.lua'" \
    -c 'lua require("test")' -- tmp.txt
fi
nvim --headless --clean \
  -c "lua package.path = package.path .. ';./?.lua;../?.lua'" \
  -c 'lua require("test")' -c "q!"
